### ISSUE TITLE
Investigate SPI flash OTA support on EMW3165

### ISSUE THREAD

**Issue by emilf** [MXCHIP-EMW/WICED-for-EMW#6]
It builds and tries to flash, but something is causing hardfaults on download_apps.

**Comment by emilf** [comment]
download_apps works now, uploading an update via ota_fr works.

However, the new app never boots for some reason.

So making progress slowly... it's hard to debug over hardware resets and not knowing what image is running.

**Comment by emilf** [comment]
Note to self... changes to wicked_apps.mk(WICED bug fix) and EMW3165.mk (for saving the wifi driver binary blob in app slot rather than internal resources, for multiapp support)

**Comment by leppie** [comment]
I was testing this over the weekend before my module just gave up.

SPI flash speed of 8000000 works most of the time. But also got issue running the apps after upload via web UI.

**Comment by BOB62** [comment]
Get-it after a few hours of debug, 
you must adjust the end of sector in the waf_platform.c in the directory Stm32F4xx/WAF 

#define PLATFORM_APP_START_SECTOR      ( FLASH_Sector_3  )
#define PLATFORM_APP_END_SECTOR        ( FLASH_Sector_7 )  instead of 13

**Comment by emilf** [comment]
OMG! Testing now... my god I've spent a lot of time on this shit....
If this works I'll build a statue in your honor

**Comment by emilf** [comment]
So far so good... patch coming up :)
