### ISSUE TITLE
problem with Segger J-Link

### ISSUE THREAD

**Issue by ammaree** [MXCHIP-EMW/WICED-for-EMW#8]
As per chat on gitter, JTAG=jlink not working. Tried to attach log but not working so text pasted below:

================================= openocd.log ===================================
Open On-Chip Debugger 0.9.0-00029-gafd5db2-dirty (2015-05-29-18:47)
Licensed under GNU GPL v2
For bug reports, read
    http://openocd.org/doc/doxygen/bugs.html
Info : JLink SWD mode enabled
trst_and_srst separate srst_gates_jtag trst_push_pull srst_push_pull connect_deassert_srst
adapter speed: 1000 kHz
adapter_nsrst_delay: 100
cortex_m reset_config sysresetreq
Error: libusb_open() failed with LIBUSB_ERROR_NOT_SUPPORTED
Error: Cannot find jlink Interface! Please check connection and permissions.

Open On-Chip Debugger 0.9.0-00029-gafd5db2-dirty (2015-05-29-18:47)
Licensed under GNU GPL v2
For bug reports, read
    http://openocd.org/doc/doxygen/bugs.html
Info : JLink SWD mode enabled
trst_and_srst separate srst_gates_jtag trst_push_pull srst_push_pull connect_deassert_srst
adapter speed: 1000 kHz
adapter_nsrst_delay: 100
cortex_m reset_config sysresetreq
Error: libusb_open() failed with LIBUSB_ERROR_NOT_SUPPORTED
Error: Cannot find jlink Interface! Please check connection and permissions.

Open On-Chip Debugger 0.9.0-00029-gafd5db2-dirty (2015-05-29-18:47)
Licensed under GNU GPL v2
For bug reports, read
    http://openocd.org/doc/doxygen/bugs.html
Info : JLink SWD mode enabled
trst_and_srst separate srst_gates_jtag trst_push_pull srst_push_pull connect_deassert_srst
adapter speed: 1000 kHz
adapter_nsrst_delay: 100
cortex_m reset_config sysresetreq
Error: libusb_open() failed with LIBUSB_ERROR_NOT_SUPPORTED
Error: Cannot find jlink Interface! Please check connection and permissions.

Open On-Chip Debugger 0.9.0-00029-gafd5db2-dirty (2015-05-29-18:47)
Licensed under GNU GPL v2
For bug reports, read
    http://openocd.org/doc/doxygen/bugs.html
Info : JLink SWD mode enabled
trst_and_srst separate srst_gates_jtag trst_push_pull srst_push_pull connect_deassert_srst
adapter speed: 1000 kHz
adapter_nsrst_delay: 100
cortex_m reset_config sysresetreq
Error: libusb_open() failed with LIBUSB_ERROR_NOT_SUPPORTED
Error: Cannot find jlink Interface! Please check connection and permissions.

============================== output from make =============================
if not exist  build\eclipse_debug\ mkdir  build\eclipse_debug\
echo Downloading DCT ...
"./tools/common/Win32/cp.exe" -f build/wwd_ping-EMW3162-FreeRTOS-LwIP-SDIO/binary/wwd_ping-EMW3162-FreeRTOS-LwIP-SDIO.elf build/eclipse_debug/last_built.elf
Downloading DCT ...
.\tools\OpenOCD\Win32\openocd-all-brcm-libftdi.exe -f ./tools/OpenOCD/jlink.cfg -f ./tools/OpenOCD/stm32f2x.cfg -f ./tools/OpenOCD/stm32f2x-flash-app.cfg -c "verify_image_checksum build/wwd_ping-EMW3162-FreeRTOS-LwIP-SDIO/DCT.stripped.elf" -c shutdown >> build/openocd_log.txt 2>&1 && echo No changes detected && "./tools/common/Win32/echo.exe" || .\tools\OpenOCD\Win32\openocd-all-brcm-libftdi.exe -f ./tools/OpenOCD/jlink.cfg -f ./tools/OpenOCD/stm32f2x.cfg -f ./tools/OpenOCD/stm32f2x-flash-app.cfg -c "flash write_image erase build/wwd_ping-EMW3162-FreeRTOS-LwIP-SDIO/DCT.stripped.elf" -c shutdown >> build/openocd_log.txt 2>&1 && echo Download complete && "./tools/common/Win32/echo.exe" || echo "***\* OpenOCD failed - ensure you have installed the driver from the drivers directory, and that the debugger is not running ***\* In Linux this may be due to USB access permissions. In a virtual machine it may be due to USB passthrough settings. Check in the task list that another OpenOCD process is not running. Check that you have the correct target and JTAG device plugged in. ***_"
"**_\* OpenOCD failed - ensure you have installed the driver from the drivers directory, and that the debugger is not running ***\* In Linux this may be due to USB access permissions. In a virtual machine it may be due to USB passthrough settings. Check in the task list that another OpenOCD process is not running. Check that you have the correct target and JTAG device plugged in. ***_"
echo Downloading Application ...
Downloading Application ...
.\tools\OpenOCD\Win32\openocd-all-brcm-libftdi.exe -f ./tools/OpenOCD/jlink.cfg -f ./tools/OpenOCD/stm32f2x.cfg -f ./tools/OpenOCD/stm32f2x-flash-app.cfg -c "verify_image_checksum build/wwd_ping-EMW3162-FreeRTOS-LwIP-SDIO/binary/wwd_ping-EMW3162-FreeRTOS-LwIP-SDIO.stripped.elf" -c shutdown >> build/openocd_log.txt 2>&1 && echo No changes detected && "./tools/common/Win32/echo.exe" || .\tools\OpenOCD\Win32\openocd-all-brcm-libftdi.exe -f ./tools/OpenOCD/jlink.cfg -f ./tools/OpenOCD/stm32f2x.cfg -f ./tools/OpenOCD/stm32f2x-flash-app.cfg -c "flash write_image erase build/wwd_ping-EMW3162-FreeRTOS-LwIP-SDIO/binary/wwd_ping-EMW3162-FreeRTOS-LwIP-SDIO.stripped.elf" -c shutdown >> build/openocd_log.txt 2>&1 && echo Download complete && "./tools/common/Win32/echo.exe" || echo "**_\* OpenOCD failed - ensure you have installed the driver from the drivers directory, and that the debugger is not running ***\* In Linux this may be due to USB access permissions. In a virtual machine it may be due to USB passthrough settings. Check in the task list that another OpenOCD process is not running. Check that you have the correct target and JTAG device plugged in. ***_"
"**_\* OpenOCD failed - ensure you have installed the driver from the drivers directory, and that the debugger is not running ***\* In Linux this may be due to USB access permissions. In a virtual machine it may be due to USB passthrough settings. Check in the task list that another OpenOCD process is not running. Check that you have the correct target and JTAG device plugged in. ****"
make.exe[1]: Leaving directory 'C:/Users/andre/Documents/WICED/WICED-SDK-3.3.1/WICED-SDK'
echo Build complete
Build complete
echo Making .gdbinit
Making .gdbinit
echo set remotetimeout 20 > .gdbinit
echo shell start /B ./tools/OpenOCD/Win32/openocd-all-brcm-libftdi.exe -f ./tools/OpenOCD/jlink.cfg -f ./tools/OpenOCD/stm32f2x.cfg -f ./tools/OpenOCD/stm32f2x_gdb_jtag.cfg -l build/openocd_log.txt >> .gdbinit

20:39:57 Build Finished (took 14s.741ms)

**Comment by emilf** [comment]
Ok.

You might have to override the default jlink drivers with libusb ones.
If that doesn't work, please try the following:

Can you give me the output of running `start /B ./tools/OpenOCD/Win32/openocd-all-brcm-libftdi.exe -f ./tools/OpenOCD/jlink.cfg`
and then install OpenOCD separately and run `openocd -f interface/jlink.cfg`

**Comment by emilf** [comment]
WICED forums issue: https://community.broadcom.com/message/1133#1133
This points to using the libusb driver and gives directions.

**Comment by emilf** [comment]
Direct link the the post with the instructions: https://community.broadcom.com/message/7920#7920

**Comment by emilf** [comment]
Platform specific, non-project specific issue.
